/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/auth`; params?: Router.UnknownInputParams; } | { pathname: `/auth/logIn`; params?: Router.UnknownInputParams; } | { pathname: `/auth/signUp`; params?: Router.UnknownInputParams; } | { pathname: `/collections`; params?: Router.UnknownInputParams; } | { pathname: `/generalInformation`; params?: Router.UnknownInputParams; } | { pathname: `/newTastingNote/WineMainColorSelection`; params?: Router.UnknownInputParams; } | { pathname: `/newTastingNote`; params?: Router.UnknownInputParams; } | { pathname: `/newTastingNote/newTastingNoteForm`; params?: Router.UnknownInputParams; } | { pathname: `/newTastingNote/wineTypeSelection`; params?: Router.UnknownInputParams; } | { pathname: `/settings/logOut`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/auth`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/logIn`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/signUp`; params?: Router.UnknownOutputParams; } | { pathname: `/collections`; params?: Router.UnknownOutputParams; } | { pathname: `/generalInformation`; params?: Router.UnknownOutputParams; } | { pathname: `/newTastingNote/WineMainColorSelection`; params?: Router.UnknownOutputParams; } | { pathname: `/newTastingNote`; params?: Router.UnknownOutputParams; } | { pathname: `/newTastingNote/newTastingNoteForm`; params?: Router.UnknownOutputParams; } | { pathname: `/newTastingNote/wineTypeSelection`; params?: Router.UnknownOutputParams; } | { pathname: `/settings/logOut`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/auth${`?${string}` | `#${string}` | ''}` | `/auth/logIn${`?${string}` | `#${string}` | ''}` | `/auth/signUp${`?${string}` | `#${string}` | ''}` | `/collections${`?${string}` | `#${string}` | ''}` | `/generalInformation${`?${string}` | `#${string}` | ''}` | `/newTastingNote/WineMainColorSelection${`?${string}` | `#${string}` | ''}` | `/newTastingNote${`?${string}` | `#${string}` | ''}` | `/newTastingNote/newTastingNoteForm${`?${string}` | `#${string}` | ''}` | `/newTastingNote/wineTypeSelection${`?${string}` | `#${string}` | ''}` | `/settings/logOut${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/auth`; params?: Router.UnknownInputParams; } | { pathname: `/auth/logIn`; params?: Router.UnknownInputParams; } | { pathname: `/auth/signUp`; params?: Router.UnknownInputParams; } | { pathname: `/collections`; params?: Router.UnknownInputParams; } | { pathname: `/generalInformation`; params?: Router.UnknownInputParams; } | { pathname: `/newTastingNote/WineMainColorSelection`; params?: Router.UnknownInputParams; } | { pathname: `/newTastingNote`; params?: Router.UnknownInputParams; } | { pathname: `/newTastingNote/newTastingNoteForm`; params?: Router.UnknownInputParams; } | { pathname: `/newTastingNote/wineTypeSelection`; params?: Router.UnknownInputParams; } | { pathname: `/settings/logOut`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
